### ISSUE TITLE
lpconvert old format

### ISSUE THREAD

**Issue by maliabd-al-majid** [potassco/libpotassco#11]
i have tried lipotassco with the data.lp file attached, and i got issue will running :
-> lpconvert --text ./data | gringo --output=text
the problem is in minimize rule it has the old format :
-output from lpconvert:

#minimize{map(2,red)=1; map(5,red)=1; map(8,red)=1; map(11,red)=1; map(14,red)=1; map(16,red)=1; map(18,red)=1; map(19,red)=1; map(22,red)=1; map(7,red)=1; map(26,red)=1; map(10,red)=1; map(24,red)=1; map(30,red)=1; map(23,red)=1; map(25,red)=1; map(3,red)=1; map(4,red)=1; map(6,red)=1; map(9,red)=1; map(12,red)=1; map(13,red)=1; map(15,red)=1; map(17,red)=1; map(20,red)=1; map(21,red)=1; map(27,red)=1; map(28,red)=1; map(29,red)=1}@0.

error is :  error: syntax error, unexpected =, expecting } or ;
[data.zip](https://github.com/potassco/libpotassco/files/6913069/data.zip)

thanks in advance.

Best Regards,
Mohamed Nadeem

**Comment by maliabd-al-majid** [comment]
i have updated lp2txt script to accept the new format "minimize"/"maximize"/"compute" removed.
but i wanted to make sure that lpconvert has the old format.

**Comment by rkaminsk** [comment]
The output of `lpconvert --text` was not really meant to be read by gringo. You also have to be careful passing a grounded program to gringo. It will scale very badly.

I don't know what you are planning to do. Maybe reification might interest you: <https://github.com/potassco/clingo/tree/master/examples/reify/simple>.
