### ISSUE TITLE
Please update to Catch2 (2.13.5+)

### ISSUE THREAD

**Issue by slyon** [potassco/libpotassco#12]
The catch1 library/test system is unmaintained and not compatible with glibc v2.34+ anymore.
`SIGSTKSZ` is not a constant anymore as of glibc 2.34+ – Catch2 has been updated to handle such situations (https://github.com/catchorg/Catch2/issues/2178), while Catch1 remains unmaintained, which makes the tests of libpotassco fail to build on newer systems (e.g. Ubuntu 22.04).

```
In file included from /<<PKGBUILDDIR>>/clasp/libpotassco/tests/main.cpp:19:
/<<PKGBUILDDIR>>/clasp/libpotassco/tests/catch.hpp:6415:41: error: array bound is not an integer constant before ‘]’ token
 6415 |         static char altStackMem[SIGSTKSZ];
      |                                         ^
/<<PKGBUILDDIR>>/clasp/libpotassco/tests/catch.hpp: In constructor ‘Catch::FatalConditionHandler::FatalConditionHandler()’:
/<<PKGBUILDDIR>>/clasp/libpotassco/tests/catch.hpp:6434:30: error: ‘altStackMem’ was not declared in this scope
 6434 |             sigStack.ss_sp = altStackMem;
      |                              ^~~~~~~~~~~
/<<PKGBUILDDIR>>/clasp/libpotassco/tests/catch.hpp: At global scope:
/<<PKGBUILDDIR>>/clasp/libpotassco/tests/catch.hpp:6466:53: error: array bound is not an integer constant before ‘]’ token
 6466 |     char FatalConditionHandler::altStackMem[SIGSTKSZ] = {};
      |                                                     ^
```

**Comment by rkaminsk** [comment]
@BenKaufmann we should do this at some point. We should also change how catch is included. Version 3 is moving away from a single header include. Since we are using cmake, it is very easy to just add catch as a submodule or subtree and use it calling `add_subdirectory`. @slyon As a quick fix, you can probably just replace the catch header by the latest catch 2 header.

**Comment by slyon** [comment]
Thank you for the feedback! I've opted to patch the files to make use of the system provided catch library in Ubuntu, which is already modified to be compatible with glibc-2.34.

http://launchpadlibrarian.net/581088471/gringo_5.4.1-3ubuntu2_5.4.1-3ubuntu3.diff.gz
https://launchpad.net/ubuntu/+source/gringo/5.4.1-3ubuntu3

**Comment by BenKaufmann** [comment]
Updated to catch v2.13.8 on dev branch.

@rkaminsk I'm fine with an upgrade to version 3 and a switch to a separate library. If you can provide corresponding PRs that would be even better :smile:
